name: github_actions
on:
  pull_request:
    branches:
      - development

jobs:
  run-checks:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Make scripts executable
        run: chmod +x .automations/*.sh
      
      - name: Run automation scripts
        run: |
          for script in .automations/*.sh; do
            echo "Running $script..."
            $script
          done
